### ISSUE TITLE
Rebuild dist and release

### ISSUE THREAD

**Issue by jkroepke** [mdgreenwald/mozilla-sops-action#157]
In #153 and #144 packages are upgrade without rebuilding dist/index.js. In fact, the source does not match the executed action js file.

Currently, I'm experiencing warnings like

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

By updating `@action/core` to 1.10 should fix that issue, but it seems like dist/index.js still using an outdated dependency.

**Comment by mdgreenwald** [comment]
Hi @jkroepke , You are correct. I generally try to merge in updates to `main` over time and let them accumulate before cutting a release. The exception I make are security vulnerabilities and bug fixes, those I will usually cut a release for as soon as I am able.

**Comment by mdgreenwald** [comment]
https://github.com/mdgreenwald/mozilla-sops-action/pull/159

**Comment by mdgreenwald** [comment]
@jkroepke https://github.com/mdgreenwald/mozilla-sops-action/releases/tag/v1.4.0

**Comment by schlomo** [comment]
Is there a way to make `mdgreenwald/mozilla-sops-action@latest` also work?

**Comment by mdgreenwald** [comment]
@schlomo Not consistently.

**Comment by schlomo** [comment]
Can I suggest a completely different approach?

The problem I'm trying to solve is using latest SOPS without manual maintenance effort.

How about you start tracking the SOPS version in the version of the `mdgreenwald/mozilla-sops-action` action so that we can then use [Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) to keep your action **and** SOPS up-to-date.

For example, `mdgreenwald/mozilla-sops-action@v3.7.3-1.4.0` would denote version `1.4.0` of your action that defaults to install SOPS in version `3.7.3`.

When SOPS releases a new version, e.g. `3.7.4`, then you would also (automatically) update to `mdgreenwald/mozilla-sops-action@v3.7.4-1.4.0` and Dependabot would be able to pick that up and offer me to update my workflows to the new release of SOPS.

Alternatively, unrelated to a new SOPS release you change something in this action then you would go and release a `mdgreenwald/mozilla-sops-action@v3.7.3-1.5.0` version of this action. Again Dependabot would pick that up.

And finally, you could use a tag like `v3` to denote SOPS `v3` without caring about the details of SOPS minor/patch or the version of your action.

What do you think @mdgreenwald?

**Comment by mdgreenwald** [comment]
I do not plan to change the tool in this way as it would be very limiting and would generate many versions. Instead I plan to fix the problematic API call, I merely need to find the time to do it. Alternatively as this is an Open Source project you are free to open a PR.
